apiVersion: v1
kind: Service
metadata:
  labels:
    name: gridvo-mosca
  name: gridvo-mosca
  namespace: gridvo
spec:
  selector:
    name: gridvo-mosca
  type: NodePort
  ports:
     - name: "wss"
       port: 443
       targetPort: 443
       nodePort: 31013
     - name: "mqtt"
       port: 1883
       targetPort: 1883
       nodePort: 31014